name: Bandit SAST Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Security Scan
        run: bandit -r . -f json -o bandit-report.json

      - name: Display Bandit Report
        run: cat bandit-report.json

      - name: Fail on Medium and High-Severity Issues
        run: |
          ISSUES=$(jq '[.results[] | select(.issue_severity=="High" or .issue_severity=="Medium")] | length' bandit-report.json)
          if [ "$ISSUES" -gt 0 ]; then
            echo "Medium or High-severity issues found: $ISSUES"
            exit 1
          fi

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      - name: Set Check Status
        uses: actions/github-script@v6
        with:
          script: |
            const conclusion = '${{ steps.bandit_scan.outcome }}' === 'success' ? 'success' : 'failure';
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'Bandit SAST Security Scan',
              head_sha: context.sha,
              status: 'completed',
              conclusion,
              output: {
                title: conclusion === 'success' ? 'No issues found' : 'Vulnerabilities detected',
                summary: 'The Bandit security scan has completed.'
              }
            });
